image: golang:1.10.2
pipelines:
  default:
    - step:
        name: Dependencies
        script:
          # Prepare the environment
          - echo -e "machine bitbucket.org\nlogin ${BITBUCKET_USERNAME}\npassword ${BITBUCKET_PASSWORD}\n" > ~/.netrc && chmod 600 ~/.netrc
          - export PATH=/go/bin:$PATH GOPATH=/go SRCDIR=/go/src/bitbucket.org/atlassian/go-vpcflow
          - mkdir -p /go/bin /go/src/bitbucket.org/atlassian && ln -s $BITBUCKET_CLONE_DIR $SRCDIR && cd $SRCDIR

          # Install dependencies
          - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          - make dep
        artifacts:
          - vendor/**
    - step:
        name: Static Analysis
        script:
          - export SRCDIR=/go/src/bitbucket.org/atlassian/go-vpcflow
          - mkdir -p /go/src/bitbucket.org/atlassian && ln -s $BITBUCKET_CLONE_DIR $SRCDIR && cd $SRCDIR
          - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b /go/bin v1.10.2
          - make lint
    - step:
        name: Build and test
        script:
          # Prepare the environment
          - export SRCDIR=/go/src/bitbucket.org/atlassian/go-vpcflow
          - mkdir -p /go/src/bitbucket.org/atlassian && ln -s $BITBUCKET_CLONE_DIR $SRCDIR && cd $SRCDIR
          - go get github.com/axw/gocov/...
          - go install github.com/axw/gocov/gocov
          - go get github.com/AlekSi/gocov-xml
          - go install github.com/AlekSi/gocov-xml
          - go get github.com/wadey/gocovmerge
          - go install github.com/wadey/gocovmerge
          - make test
          - make coverage

