# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.55"

[[constraint]]
  name = "gonum.org/v1/gonum"
  revision = "572d9101fe4fdede494f26999a59d09229b7c11b"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
